[project]
name = "birds-watcher"
version = "0.1.0"
description = "watch and record birds with a camera"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.0",
    "numpy>=2.2.1",
    "opencv-python>=4.11.0.86",
]
